### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by mateuszluczak** [dupski/subpackage#1]
Hey I really like this module as it makes package.json configuration for project nice and tidy.

I have only one question - have you considered supporting yarn (maybe based on existance of yarn.lock file)?

**Comment by dupski** [comment]
Hey, thanks for your feedback!

Yep yarn would be cool, not something I need right now but will definitely look to add it when I do. Happy to accept PRs too... :)

**Comment by mateuszluczak** [comment]
I have created the PR #2

**Comment by dupski** [comment]
#merged. Cheers :)
