### ISSUE TITLE
Stop executing script when `--watch` found 

### ISSUE THREAD

**Issue by mitraparthib3** [dupski/subpackage#3]
I just started using this package, I must say its super cool. So far I found one blocker. When I was trying `sudo npm run start-local` from root dir it stopped executing the commands the moment it found `--watch`.

Here are the package.json:
Parent package.json: 
`  "scripts": {
    "postinstall": "subpkg install",
    "build": "subpkg run clean; subpkg run build",
	  "postbuild": "cp -r client/dist/* server/build/public; cp package.json server/build/",
    "start": "node index.js",
    "start-local": "subpkg run clean; subpkg run start"
  },`

client package.json:
`"scripts": {
    "postinstall": "echo client packages installed",
    "start": "npm-run-all --parallel test:watch open:src lint:watch",
    "open:src": "babel-node ./tools/srcServer",
    "lint:watch": "npm run lint -- --watch",
    "clean": "npm run remove-dist && mkdir dist",
    "remove-dist": "rimraf ./dist",
    "build": "babel-node tools/build.js",
  }`

server package.json:
`"scripts": {
    "postinstall": "echo server packages installed",
    "build:watch": "npm run build --watch",
    "clean": "rimraf build && mkdir -p build/public",
    "lint": "esw -f simple-detail --color src",
    "lint:watch": "npm run lint -- --watch",
    "prestart:dev": "npm run build",
    "serve:src": "babel-watch ./src/index.js",
    "start": "npm-run-all --parallel serve:src lint:watch"
  }`

**Comment by dupski** [comment]
Hey @mitraparthib3 , I'm glad you're finding this package helpful.

Unfortunately I think Watch mode is one thing that won't work well with this tool, it is only designed to run one command at a time (e.g. run Build once for each of your packages).

If you want to run your server and client in watch mode together, I'd recommend having one Npm command for each and running them in seperate consoles

**Comment by mitraparthib3** [comment]
Thanks @dupski! Like you mentioned, I am running two separate start command as a workaround.
